"""empty message

Revision ID: 60121fa02fc2
Revises: 
Create Date: 2019-04-09 01:12:41.704679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60121fa02fc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('publicationdate', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('desc', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articlecategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.String(length=250), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['categorie_id'], ['categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geotag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publishdate', sa.String(length=250), nullable=True),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geotag')
    op.drop_table('articlecategorie')
    op.drop_table('categorie')
    op.drop_table('article')
    # ### end Alembic commands ###
